export const users = [
  {
    userID: "1",
    name: "Amit Kumar",
    email: "amit.kumar@gmail.com",
    password: "amit@123",
    followers: 1000,
    following: 500,
  },
  {
    userID: "2",
    name: "Priya Sharma",
    email: "priya.sharma@gmail.com",
    password: "amit@123",
    followers: 2000,
    following: 1000,
  },
  {
    userID: "3",
    name: "Rajesh Singh",
    email: "rajesh.singh@gmail.com",
    password: "amit@123",
    followers: 1500,
    following: 750,
  },
  {
    userID: "4",
    name: "Sneha Patel",
    email: "sneha.patel@gmail.com",
    password: "amit@123",
    followers: 2500,
    following: 1250,
  },
  {
    userID: "5",
    name: "Vikram Verma",
    email: "vikram.verma@gmail.com",
    password: "amit@123",
    followers: 3000,
    following: 1500,
  },
];

export const tweets = [
  {
    tweetID: "1",
    tweet:
      "Excited to start my new project today! It's going to be a challenging yet rewarding experience. Can't wait to share more updates.",
    tweetDate: "2023-09-20",
    time: "08:00",
    likes: 120,
    views: 500,
    userID: "1",
    has_tag: "#NewProject",
  },
  {
    tweetID: "2",
    tweet:
      "Witnessed a beautiful sunrise this morning. The colors were absolutely breathtaking. Nature truly is the best artist.",
    tweetDate: "2023-09-20",
    time: "06:30",
    likes: 75,
    views: 300,
    userID: "2",
    has_tag: "#NatureLover",
  },
  {
    tweetID: "3",
    tweet:
      "Just finished a great book! It was an intriguing story that kept me hooked till the end. Highly recommend it to all book lovers out there.",
    tweetDate: "2023-09-19",
    time: "22:00",
    likes: 105,
    views: 450,
    userID: "3",
    has_tag: "#BookLover",
  },
  {
    tweetID: "4",
    tweet:
      "Had a successful meeting with the team today. Discussed some innovative ideas and made progress on our project. Looking forward to more such productive sessions.",
    tweetDate: "2023-09-19",
    time: "16:00",
    likes: 98,
    views: 600,
    userID: "4",
    has_tag: "#TeamWork",
  },
  {
    tweetID: "5",
    tweet:
      "Loving the new updates on my favorite app. The user interface is much more intuitive and the new features are definitely a game changer. Kudos to the team behind it!",
    tweetDate: "2023-09-18",
    time: "14:00",
    likes: 34,
    views: 700,
    userID: "5",
    has_tag: "#TechGeek",
  },
  {
    tweetID: "6",
    tweet:
      "Can't wait for the weekend! Looking forward to some relaxation and quality time with family. Also planning to catch up on some reading.",
    tweetDate: "2023-09-18",
    time: "18:00",
    likes: 200,
    views: 800,
    userID: "1",
    has_tag: "#FridayFeeling",
  },
  {
    tweetID: "7",
    tweet:
      "Had a great workout session today. Feeling energized and ready to take on the day! Remember, a healthy body leads to a healthy mind.",
    tweetDate: "2023-09-17",
    time: "20:00",
    likes: 150,
    views: 550,
    userID: "2",
    has_tag: "#FitnessGoals",
  },
  {
    tweetID: "8",
    tweet:
      "Enjoying a delicious homemade meal tonight. Cooking can be therapeutic and eating home-cooked food is always a delight.",
    tweetDate: "2023-09-17",
    time: "21:00",
    likes: 170,
    views: 650,
    userID: "3",
    has_tag: "#Foodie",
  },
  {
    tweetID: "9",
    tweet:
      "Spending quality time with family today. It's important to cherish these moments and make lasting memories. Family always comes first!",
    tweetDate: "2023-09-16",
    time: "19:00",
    likes: 180,
    views: 700,
    userID: "4",
    has_tag: "#FamilyFirst",
  },
  {
    tweetID: "10",
    tweet:
      "Exploring new places is always an adventure. You get to learn about different cultures, meet new people and make unforgettable memories. Can't wait for my next trip!",
    tweetDate: "2023-09-16",
    time: "15:00",
    likes: 190,
    views: 750,
    userID: "5",
    has_tag: "#Wanderlust",
  },
];
